name: Build and Release Firmware

on:
  push:
    tags:
      - 'v*'  # Wird ausgelöst, wenn du einen Tag mit v setzt, z.B. v1.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('platformio.ini') }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      
      - name: Build Firmware
        run: |
          platformio run -e nodemcuv2
      
      - name: Copy firmware files to web folder
        run: |
          cp .pio/build/nodemcuv2/firmware.bin web/
          pio run -t buildfs
          cp .pio/build/nodemcuv2/littlefs.bin web/
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Upload Firmware Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./web/firmware.bin
          asset_name: firmware.bin
          asset_content_type: application/octet-stream
      
      - name: Upload LittleFS Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./web/littlefs.bin
          asset_name: littlefs.bin
          asset_content_type: application/octet-stream

      - name: Update Version
        run: |
          python .github/scripts/update_version.py ${{ github.ref_name }}
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/main.cpp web/manifest.json
          git commit -m "Update version to ${{ github.ref_name }}"
          git push